### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/benchmark-runner#4]
There is currently no testing framework.

**Comment by ashwinimanoj** [comment]
Hi, I would like to take this up! Would adding jest be fine?

**Comment by RichardLitt** [comment]
That wouldn't be a problem for me! @aphelionz what do you think?

**Comment by aphelionz** [comment]
Absolutely @ashwinimanoj, please do!

**Comment by aphelionz** [comment]
@ashwinimanoj actually, we use mocha elsewhere in the org, would that be ok?

**Comment by ashwinimanoj** [comment]
Oh sure, I can make Mocha happen. Thanks! It's sort of my first open source contribution btw!

**Comment by aphelionz** [comment]
Welcome! Please feel free to reach out here or on any of the chat rooms if you have more questions / want to get more involved. The chat links are in the badges at the top of https://github.com/orbitdb/welcome

**Comment by ashwinimanoj** [comment]
@aphelionz Thanks a lot! I hope I can do a good job here! :) I was able to get Mocha working, and added in sinon to spy on a module, I hope that's okay?

**Comment by aphelionz** [comment]
Thanks @ashwinimanoj ! I think we can close this.
